version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "marcosraimondi1/webrtc-backend"
    ports:
      - "80:8080" # host : contenedor
      - "3001:3001" # host : contenedor
